# Generated by Django 5.0.7 on 2024-07-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_done", "created"]},
        ),
    ]
